// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	message "MyDouSheng/app/message/cmd/api/internal/handler/message"
	"MyDouSheng/app/message/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.JwtauthMiddleware},
			[]rest.Route{
				{
					// sendmessage
					Method:  http.MethodPost,
					Path:    "/action",
					Handler: message.SendmessageHandler(serverCtx),
				},
				{
					// getmessagelist
					Method:  http.MethodGet,
					Path:    "/chat",
					Handler: message.GetmessagelistHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/douyin/message"),
	)
}
