// Code generated by goctl. DO NOT EDIT.
package types

type Follow struct {
	UserId        int64  `json:"id"`             // 用户的唯一标识
	Username      string `json:"name"`           // 用户名称
	FollowerCount int64  `json:"follower_count"` // 粉丝总数
	IsFollow      bool   `json:"is_follow"`
}

type Friend struct {
	UserId          int64  `json:"id"`             // 用户的唯一标识
	Username        string `json:"name"`           // 用户名称
	FollowingCount  int64  `json:"follow_count"`   // 关注总数
	FollowerCount   int64  `json:"follower_count"` // 粉丝总数
	Avator          string `json:"avator"`         // 头像
	BackgroundImage string `json:"background_image"`
	IsFollow        bool   `json:"is_follow"`       //
	Signature       string `json:"signature"`       // 个人简介
	TotalFavorited  int64  `json:"total_favorited"` // 获赞数
	WorkCount       int64  `json:"work_count"`      // 作品总数
	FavoriteCount   int64  `json:"favorite_count"`  // 点赞数
	Message         string `json:"message"`         // 和好友最新聊天记录
	MsgType         int64  `json:"msgType"`         // message消息的类型，0 => 当前请求用户接收的消息， 1 => 当前请求用户发送的消息
}

type GetAttentionReq struct {
	Token      string `json:"token"`
	ToUserId   int64  `json:"to_user_id"`
	ActionType int64  `json:"action_type"`
}

type GetAttentionResp struct {
	StatusMsg string `json:"status_msg"`
}

type GetFanlistReq struct {
	Token  string `json:"token"`
	UserId int64  `json:"user_id"`
}

type GetFanlistResp struct {
	StatusMsg string   `json:"status_msg"`
	UserList  []Follow `json:"user_list"`
}

type GetFollowlistReq struct {
	Token  string `json:"token"`
	UserId int64  `json:"user_id"`
}

type GetFollowlistResp struct {
	StatusMsg string   `json:"status_msg"`
	UserList  []Follow `json:"user_list"`
}

type GetFriendsReq struct {
	Token  string `json:"token"`
	UserId int64  `json:"user_id"`
}

type GetFriendsResp struct {
	StatusMsg string   `json:"status_msg"`
	UserList  []Friend `json:"user_list"`
}

type User struct {
	UserId          int64  `json:"id"`             // 用户的唯一标识
	Username        string `json:"name"`           // 用户名称
	FollowingCount  int64  `json:"follow_count"`   // 关注总数
	FollowerCount   int64  `json:"follower_count"` // 粉丝总数
	Avator          string `json:"avator"`         // 头像
	BackgroundImage string `json:"background_image"`
	IsFollow        bool   `json:"is_follow"`       // true以关注, false未关注
	Signature       string `json:"signature"`       // 个人简介
	TotalFavorited  int64  `json:"total_favorited"` // 获赞数
	WorkCount       int64  `json:"work_count"`      // 作品总数
	FavoriteCount   int64  `json:"favorite_count"`  // 点赞数
}

type UserInfoReq struct {
	UserId int64  `json:"user_id"` // 用户Id
	Token  string `json:"token"`
}

type UserInfoRsp struct {
	StatusCode int64  `json:"status_code"` // 状态码
	StatusMsg  string `json:"status_msg"`  //返回状态描述
	UserInfo   User   `json:"userInfo"`    // 用户信息
}

type UserLoginReq struct {
	Username string `json:"username"` // 用户名
	Password string `json:"password"` // 密码
}

type UserLoginRsp struct {
	StatusCode int64  `json:"status_code"` // 状态码
	StatusMsg  string `json:"status_msg"`  //状态信息
	UserId     int64  `json:"user_id"`     // 用户名Id
	Token      string `json:"token"`       //token
}

type UserRegisterReq struct {
	Username string `json:"username"` // 用户名
	Password string `json:"password"` // 用户密码
}

type UserRegisterRsp struct {
	StatusCode int64  `json:"status_code"` // 状态码
	StatusMsg  string `json:"status_msg"`  //状态信息
	UserId     int64  `json:"user_id"`     // 用户名Id
	Token      string `json:"token"`       //token
}
