// Code generated by goctl. DO NOT EDIT.
// Source: relation.proto

package server

import (
	"context"

	"MyDouSheng/app/relation/cmd/rpc/internal/logic"
	"MyDouSheng/app/relation/cmd/rpc/internal/svc"
	"MyDouSheng/app/relation/cmd/rpc/pb"
)

type RelationserviceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedRelationserviceServer
}

func NewRelationserviceServer(svcCtx *svc.ServiceContext) *RelationserviceServer {
	return &RelationserviceServer{
		svcCtx: svcCtx,
	}
}

func (s *RelationserviceServer) GetAttention(ctx context.Context, in *pb.GetAttentionReq) (*pb.GetAttentionResp, error) {
	l := logic.NewGetAttentionLogic(ctx, s.svcCtx)
	return l.GetAttention(in)
}

func (s *RelationserviceServer) GetAttentionRollback(ctx context.Context, in *pb.GetAttentionReq) (*pb.GetAttentionResp, error) {
	l := logic.NewGetAttentionRollbackLogic(ctx, s.svcCtx)
	return l.GetAttentionRollback(in)
}

func (s *RelationserviceServer) GetFollowlist(ctx context.Context, in *pb.GetFollowlistReq) (*pb.GetFollowlistResp, error) {
	l := logic.NewGetFollowlistLogic(ctx, s.svcCtx)
	return l.GetFollowlist(in)
}

func (s *RelationserviceServer) GetFanlist(ctx context.Context, in *pb.GetFanlistReq) (*pb.GetFanlistResp, error) {
	l := logic.NewGetFanlistLogic(ctx, s.svcCtx)
	return l.GetFanlist(in)
}

func (s *RelationserviceServer) GetFriends(ctx context.Context, in *pb.GetFriendsReq) (*pb.GetFriendsResp, error) {
	l := logic.NewGetFriendsLogic(ctx, s.svcCtx)
	return l.GetFriends(in)
}
