// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	user "MyDouSheng/app/user/cmd/api/internal/handler/user"
	"MyDouSheng/app/user/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// login
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: user.UserLoginHandler(serverCtx),
			},
			{
				// register
				Method:  http.MethodPost,
				Path:    "/register",
				Handler: user.UserRegisterHandler(serverCtx),
			},
		},
		rest.WithPrefix("/douyin/user"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// userinfo
				Method:  http.MethodGet,
				Path:    "/user",
				Handler: user.GetUserInfoHandler(serverCtx),
			},
		},
		rest.WithPrefix("/douyin"),
	)
}
