// Code generated by goctl. DO NOT EDIT.
// Source: video.proto

package server

import (
	"context"

	"MyDouSheng/app/video/cmd/rpc/internal/logic"
	"MyDouSheng/app/video/cmd/rpc/internal/svc"
	"MyDouSheng/app/video/cmd/rpc/pb"
)

type VideoserviceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedVideoserviceServer
}

func NewVideoserviceServer(svcCtx *svc.ServiceContext) *VideoserviceServer {
	return &VideoserviceServer{
		svcCtx: svcCtx,
	}
}

func (s *VideoserviceServer) PublishVideo(ctx context.Context, in *pb.PublishVideoReq) (*pb.PublishVideoResp, error) {
	l := logic.NewPublishVideoLogic(ctx, s.svcCtx)
	return l.PublishVideo(in)
}

func (s *VideoserviceServer) PublishVideoRollback(ctx context.Context, in *pb.PublishVideoReq) (*pb.PublishVideoResp, error) {
	l := logic.NewPublishVideoRollbackLogic(ctx, s.svcCtx)
	return l.PublishVideoRollback(in)
}

func (s *VideoserviceServer) GetVideolsit(ctx context.Context, in *pb.GetVideolistReq) (*pb.GetVideolistResp, error) {
	l := logic.NewGetVideolsitLogic(ctx, s.svcCtx)
	return l.GetVideolsit(in)
}
