// Code generated by goctl. DO NOT EDIT.
package types

type GetFeedReq struct {
	Token      string `json:"token"`
	LatestTime string `json:"latest_time"`
}

type GetFeedResp struct {
	StatusCode int64   `json:"status_code"`
	StatusMsg  string  `json:"status_msg"`
	VideoList  []Video `json:"video_list"`
}

type GetVideoListReq struct {
	Token  string `json:"token"`
	Userid int64  `json:"user_id"`
}

type GetVideoListResp struct {
	StatusCode int64   `json:"status_code"`
	StatusMsg  string  `json:"status_msg"`
	VideoList  []Video `json:"video_list"`
}

type PublishVideoReq struct {
	Data  string `json:"data"`
	Title string `json:"title"`
}

type PublishVideoResp struct {
	StatusCode int64  `json:"status_code"`
	StatusMsg  string `json:"status_msg"`
}

type User struct {
	UserId          int64  `json:"id"`             // 用户的唯一标识
	Username        string `json:"name"`           // 用户名称
	FollowingCount  int64  `json:"follow_count"`   // 关注总数
	FollowerCount   int64  `json:"follower_count"` // 粉丝总数
	Avator          string `json:"avator"`         // 头像
	BackgroundImage string `json:"background_image"`
	IsFollow        bool   `json:"is_follow"`       // true以关注, false未关注
	Signature       string `json:"signature"`       // 个人简介
	TotalFavorited  int64  `json:"total_favorited"` // 获赞数
	WorkCount       int64  `json:"work_count"`      // 作品总数
	FavoriteCount   int64  `json:"favorite_count"`  // 点赞数
}

type UserInfoReq struct {
	UserId int64  `json:"user_id"` // 用户Id
	Token  string `json:"token"`
}

type UserInfoRsp struct {
	StatusCode int64  `json:"status_code"` // 状态码
	StatusMsg  string `json:"status_msg"`  //返回状态描述
	UserInfo   User   `json:"userInfo"`    // 用户信息
}

type UserLoginReq struct {
	Username string `json:"username"` // 用户名
	Password string `json:"password"` // 密码
}

type UserLoginRsp struct {
	StatusCode int64  `json:"status_code"` // 状态码
	StatusMsg  string `json:"status_msg"`  //状态信息
	UserId     int64  `json:"user_id"`     // 用户名Id
	Token      string `json:"token"`       //token
}

type UserRegisterReq struct {
	Username string `json:"username"` // 用户名
	Password string `json:"password"` // 用户密码
}

type UserRegisterRsp struct {
	StatusCode int64  `json:"status_code"` // 状态码
	StatusMsg  string `json:"status_msg"`  //状态信息
	UserId     int64  `json:"user_id"`     // 用户名Id
	Token      string `json:"token"`       //token
}

type Video struct {
	VideoId       string `json:"video_id"`
	Author        User   `json:"author"`
	PlayUrl       string `json:"play_url"`
	CoverUrl      string `json:"cover_url"`
	FavoriteCount string `json:"favorite_count"`
	CommentCount  string `json:"comment_count"`
	IsFavorite    bool   `json:"is_favorite"`
	Title         string `json:"title"`
}
