// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	video "MyDouSheng/app/video/cmd/api/internal/handler/video"
	"MyDouSheng/app/video/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// getfeed
				Method:  http.MethodGet,
				Path:    "/feed",
				Handler: video.GetFeedHandler(serverCtx),
			},
			{
				// publishvideo
				Method:  http.MethodPost,
				Path:    "/publish/action",
				Handler: video.PublishvideoHandler(serverCtx),
			},
			{
				// getvideolist
				Method:  http.MethodGet,
				Path:    "/publish/list",
				Handler: video.GetvideolistHandler(serverCtx),
			},
		},
		rest.WithPrefix("/douyin"),
	)
}
