// Code generated by goctl. DO NOT EDIT.
// Source: message.proto

package server

import (
	"context"

	"MyDouSheng/app/message/cmd/rpc/internal/logic"
	"MyDouSheng/app/message/cmd/rpc/internal/svc"
	"MyDouSheng/app/message/cmd/rpc/pb"
)

type MessageserviceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedMessageserviceServer
}

func NewMessageserviceServer(svcCtx *svc.ServiceContext) *MessageserviceServer {
	return &MessageserviceServer{
		svcCtx: svcCtx,
	}
}

func (s *MessageserviceServer) SendMessage(ctx context.Context, in *pb.SendMessageReq) (*pb.SendMessageResp, error) {
	l := logic.NewSendMessageLogic(ctx, s.svcCtx)
	return l.SendMessage(in)
}

func (s *MessageserviceServer) GetMessageList(ctx context.Context, in *pb.GetMessagesReq) (*pb.GetMessagesResp, error) {
	l := logic.NewGetMessageListLogic(ctx, s.svcCtx)
	return l.GetMessageList(in)
}
