// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	relation "MyDouSheng/app/relation/cmd/api/internal/handler/relation"
	"MyDouSheng/app/relation/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// getattention
				Method:  http.MethodGet,
				Path:    "/action",
				Handler: relation.GetAttentionHandler(serverCtx),
			},
			{
				// getfollowlist
				Method:  http.MethodGet,
				Path:    "/follow/list",
				Handler: relation.GetFollowlistHandler(serverCtx),
			},
			{
				// getfanlist
				Method:  http.MethodGet,
				Path:    "/follower/lsit",
				Handler: relation.GetFunlistHandler(serverCtx),
			},
			{
				// getfriends
				Method:  http.MethodGet,
				Path:    "/friend/list",
				Handler: relation.GetfriendsHandler(serverCtx),
			},
		},
		rest.WithPrefix("/douyin/relation"),
	)
}
