// Code generated by goctl. DO NOT EDIT.
package types

type GetMessagesReq struct {
	Token    string `json:"token"`
	ToUserId int64  `json:"to_user_id"`
}

type GetMessagesResp struct {
	StatusMsg string    `json:"status_msg"`
	Messages  []Message `json:"message_list"`
}

type Message struct {
	Id         int64  `json:"id"`           // 消息ID
	FromUserId int64  `json:"from_user_id"` // 发送消息的userId
	ToUserId   int64  `json:"to_user_id"`   // 接受消息的userId
	Content    string `json:"content"`      // 消息内容
	CreateTime int64  `json:"create_time"`  // 消息创建时间
}

type SendMessageReq struct {
	Token      string `json:"token"`
	ToUserId   int64  `json:"to_user_id"`
	ActionType int64  `json:"action_type"`
	Content    string `json:"content"`
}

type SendMessageResp struct {
	StatusMsg string `json:"status_msg"`
}
